# Generated by Django 5.1.2 on 2026-02-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=120)),
                ('org', models.CharField(max_length=140)),
                ('start', models.CharField(max_length=40)),
                ('end', models.CharField(blank=True, max_length=40)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('headline', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('location', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('github', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('resume_link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('tagline', models.CharField(max_length=220)),
                ('description', models.TextField()),
                ('tech_stack', models.CharField(max_length=220)),
                ('live_demo', models.URLField(blank=True)),
                ('github_repo', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('level', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
